- color: blue
  hsv:
    high:
    - 99
    - 255
    - 255
    low:
    - 96
    - 98
    - 44
- color: green
  hsv:
    high:
    - 74
    - 250
    - 255
    low:
    - 39
    - 30
    - 109
- color: purple
  hsv:
    high:
    - 151
    - 255
    - 255
    low:
    - 111
    - 0
    - 0
- color: red
  hsv:
    high:
    - 8
    - 255
    - 255
    low:
    - 0
    - 65
    - 0
- color: orange
  hsv:
    high:
    - 12
    - 232
    - 179
    low:
    - 4
    - 54
    - 85
