- color: blue
  hsv:
    high:
    - 99
    - 255
    - 255
    low:
    - 96
    - 98
    - 44
- color: green
  hsv:
    high:
    - 93
    - 213
    - 143
    low:
    - 80
    - 38
    - 61
- color: purple
  hsv:
    high:
    - 151
    - 255
    - 255
    low:
    - 111
    - 0
    - 0
- color: red
  hsv:
    high:
    - 180
    - 255
    - 255
    low:
    - 132
    - 74
    - 141
- color: orange
  hsv:
    high:
    - 12
    - 232
    - 179
    low:
    - 4
    - 54
    - 85