- color: blue
  hsv:
    high:
    - 106
    - 255
    - 209
    low:
    - 97
    - 109
    - 148
- color: green
  hsv:
    high:
    - 92
    - 244
    - 148
    low:
    - 83
    - 56
    - 70
- color: purple
  hsv:
    high:
    - 163
    - 255
    - 135
    low:
    - 113
    - 40
    - 74
- color: red
  hsv:
    high:
    - 180
    - 255
    - 255
    low:
    - 132
    - 74
    - 141
- color: orange
  hsv:
    high:
    - 6
    - 255
    - 240
    low:
    - 0
    - 66
    - 146
- color: yellow
  hsv:
    high:
    - 41
    - 197
    - 255
    low:
    - 21
    - 49
    - 67