/**:
  ros__parameters:
  # Calibration parameters in meters (m)
    calibration:
      tags:
        tag_1:
          x: -0.1016
          y: 0.4318
        tag_2:
          x: 0.762
          y: 0.4318
        tag_3:
          x: 0.762
          y: -0.508
        tag_4:
          x: -0.1016
          y: -0.508