/**:
  ros__parameters:
    # Target Detection Parameters:
    default_color: blue
    base_frame: base
    gripper_frame: fer_hand_tcp
    color_path: calibrated_colors.yaml

    # Set the Drop pad calibration range:
    pad_start: 5
    pad_end: 10

    # Calibration parameters in meters (m)
    calibration:
      tags:
        tag_1:
          x: 0.765
          y: 0.4572
        tag_2:
          x: 0.765
          y: -0.54
        tag_3:
          x: -0.15
          y: -0.54
        tag_4:
          x: -0.15
          y: 0.4572

    # Set the location of color switching block:
    color_switch_x: 0.65
    color_switch_y: -0.0127
    color_switch_z: 0.1524