/**:
  ros__parameters:
    # Target Detection Parameters:
    default_color: blue
    base_frame: base
    gripper_frame: fer_hand_tcp
    color_path: calibrated_colors.yaml

    # Calibration parameters in meters (m)
    calibration:
      tags:
        tag_1:
          x: -0.1143
          y: 0.4572
        tag_2:
          x: 0.76835
          y: 0.4475
        tag_3:
          x: 0.76835
          y: -0.5207
        tag_4:
          x: -0.1143
          y: -0.5207