- name: "table"
  pose:
    position:
      x: 0.15
      y: 0.0
      z: -0.501
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1  # SolidPrimitive.BOX
    # Approx Values [0.606,0.54, 1.0], but I want table larger out front:
    dimensions: [0.85, 0.54, 1.0]

# Bottom of the bug world base:
- name: "bug_world_base"
  pose:
    position:
      x: 0.4482
      y: -0.0254
      z: 0.0015875
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.6858, 0.9906, 0.003175]

# Right wing of the world base
- name: "bug_world_base_rwing"
  pose:
    position:
      x: -0.00736
      y: 0.3061
      z: 0.0015875
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.2794, 0.3302, 0.003175]
  
# Left wing of the world base
- name: "bug_world_base_lwing"
  pose:
    position:
      x: -0.00736
      y: -0.3569
      z: 0.0015875
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.2794, 0.3302, 0.003175]

# Right wall of the world:
- name: "bug_world_base_rwall"
  pose:
    position:
      x: 0.3127
      y: 0.4496
      z: 0.0366
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.915, 0.038, 0.0762]

# Left wall of the world:
- name: "bug_world_base_lwall"
  pose:
    position:
      x: 0.3127
      y: -0.5004
      z: 0.0366
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.915, 0.038, 0.0762]

#Front wall of the world:
- name: "bug_world_base_fwall"
  pose:
    position:
      x: 0.7861
      y: -0.0254
      z: 0.0366
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.038, 0.991, 0.0762]

# Rear left wall of the world:
- name: "bug_world_base_rlwall"
  pose:
    position:
      x: -0.1623
      y: -0.3554
      z: 0.0366
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.038, 0.33, 0.0762]

# Rear right wall of the world:
- name: "bug_world_base_rrwall"
  pose:
    position:
      x: -0.1623
      y: 0.3046
      z: 0.0366
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.038,0.33, 0.0762]

# Rear center wall of the world:
- name: "bug_world_base_rcwall"
  pose:
    position:
      x: 0.1127
      y: -0.0254
      z: 0.0366
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.038,0.406, 0.0762]

# Rear center-right wall of the world:
- name: "bug_world_base_rcrwall"
  pose:
    position:
      x: -0.0241
      y: -0.2054
      z: 0.0366
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.25,0.038, 0.0762]

# Rear center-left wall of the world:
- name: "bug_world_base_rclwall"
  pose:
    position:
      x: -0.0241
      y: 0.1546
      z: 0.0366
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.25,0.038, 0.0762]

  # Front Center Pillar:
- name: "bug_world_base_cpillar"
  pose:
    position:
      x: 0.7607
      y: -0.0254
      z: 0.0728
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.1016,0.1016, 0.1524]



