- name: "table"
  pose:
    position:
      x: 0.15
      y: 0.0
      z: -0.501
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1  # SolidPrimitive.BOX
    # Approx Values [0.606,0.54, 1.0], but I want table larger out front:
    dimensions: [0.85, 0.54, 1.0]

# Bottom of the bug world base:
- name: "bug_world_base"
  pose:
    position:
      x: 0.425
      y: 0.0
      z: 0.0125
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.686, 0.991, 0.025]

# Right wing of the world base
- name: "bug_world_base_rwing"
  pose:
    position:
      x: -0.055
      y: -0.3315
      z: 0.0125
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.279, 0.33, 0.025]
  
# Left wing of the world base
- name: "bug_world_base_lwing"
  pose:
    position:
      x: -0.055
      y: 0.3315
      z: 0.0125
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.279, 0.33, 0.025]

# Right wall of the world:
- name: "bug_world_base_rwall"
  pose:
    position:
      x: 0.3
      y: -0.475
      z: 0.062
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.915, 0.038, 0.076]

# Left wall of the world:
- name: "bug_world_base_lwall"
  pose:
    position:
      x: 0.3
      y: 0.475
      z: 0.062
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.915, 0.038, 0.076]

#Front wall of the world:
- name: "bug_world_base_fwall"
  pose:
    position:
      x: 0.748
      y: 0.0
      z: 0.062
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.038, 0.991, 0.076]

# Rear left wall of the world:
- name: "bug_world_base_rlwall"
  pose:
    position:
      x: -0.175
      y: 0.33
      z: 0.062
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.038, 0.33, 0.076]

# Rear right wall of the world:
- name: "bug_world_base_rrwall"
  pose:
    position:
      x: -0.175
      y: -0.33
      z: 0.062
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.038,0.33, 0.076]

# Rear center wall of the world:
- name: "bug_world_base_rcwall"
  pose:
    position:
      x: 0.10
      y: 0.0
      z: 0.062
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.038,0.406, 0.076]

# Rear center-right wall of the world:
- name: "bug_world_base_rcrwall"
  pose:
    position:
      x: -0.04
      y: 0.18
      z: 0.062
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.25,0.038, 0.076]

# Rear center-left wall of the world:
- name: "bug_world_base_rclwall"
  pose:
    position:
      x: -0.04
      y: -0.18
      z: 0.062
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.25,0.038, 0.076]


