- name: "table"
  pose:
    position:
      x: 0.25
      y: 0.0
      z: -0.501
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1  # SolidPrimitive.BOX
    # Approx Values [0.606,0.54, 1.0], but I want table larger out front:
    dimensions: [0.85, 0.54, 1.0]

- name: "block"
  pose:
    position:
      x: 0.3
      y: 0.225
      z: 0.035
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.03, 0.03, 0.05]

- name: "obstacle"
  pose:
    position:
      x: 0.45
      y: 0.0
      z: 0.125
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  size:
    type: 1
    dimensions: [0.25, 0.025, 0.245]
