- color: blue
  hsv:
    high:
    - 106
    - 255
    - 209
    low:
    - 97
    - 109
    - 148
- color: green
  hsv:
    high:
    - 87
    - 255
    - 255
    low:
    - 74
    - 103
    - 90
- color: purple
  hsv:
    high:
    - 163
    - 255
    - 135
    low:
    - 113
    - 40
    - 74
- color: pink
  hsv:
    high:
    - 173
    - 255
    - 210
    low:
    - 162
    - 95
    - 129
- color: orange
  hsv:
    high:
    - 6
    - 255
    - 240
    low:
    - 0
    - 66
    - 146
- color: yellow
  hsv:
    high:
    - 41
    - 197
    - 255
    low:
    - 21
    - 49
    - 67