- color: blue
  hsv:
    high:
    - 105
    - 255
    - 255
    low:
    - 83
    - 149
    - 100
- color: green
  hsv:
    high:
    - 96
    - 255
    - 75
    low:
    - 78
    - 145
    - 29
- color: purple
  hsv:
    high:
    - 180
    - 255
    - 78
    low:
    - 99
    - 26
    - 0
- color: pink
  hsv:
    high:
    - 180
    - 212
    - 134
    low:
    - 137
    - 103
    - 94
- color: orange
  hsv:
    high:
    - 15
    - 249
    - 255
    low:
    - 0
    - 160
    - 121
- color: yellow
  hsv:
    high:
    - 36
    - 179
    - 167
    low:
    - 16
    - 93
    - 114